# Designed to be triggered by github action application chart
# This workflow will only be triggered in the context of the 'develop branch'
name: package-index
on:
  workflow_dispatch:
    inputs:
      appRepo:
        description: '🛑 NOT FOR MANUAL USE!!! Repo of the newly updated Helm Chart.'
        required: true
        type: string

jobs:
  clone-package-index:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - name: Clone App Repo 
      run: |
        mkdir /tmp/${{ github.repository_owner }}
        cd /tmp/${{ github.repository_owner }}
        git clone https://github.com/${{ inputs.appRepo }}.git .

    - name: Check for Helx-Charts Package Updates
      if: ${{ inputs.appRepo == 'helxplatform/helx-chart'}}
      run: |
        cd /tmp/${{ github.repository_owner }}
        helm repo add helx-charts https://helxplatform.github.io/helm-charts
        helm repo update 
        helm dependency update ./charts/image-utils
        helm dependency update
        helm package charts/ambassador
        helm package charts/backup-pvc-cronjob
        helm package charts/image-utils
        helm package charts/nfs-server
        helm package charts/nfsrods
        helm package charts/nginx
        helm package charts/pod-reaper
        
    - name: Package Chart 
      run: |
        cd /tmp
        helm package --dependency-update ./${{ github.repository_owner }} --destination ${{ github.workspace }}/docs
        helm package --dependency-update ./${{ github.repository_owner }} --destination /tmp

    - name: Index Package
      run: | 
        cp ${{ github.workspace }}/docs/index.yaml /tmp 
        helm repo index --merge /tmp/index.yaml --url=https://helxplatform.github.io/helm-charts/ ${{ github.workspace }}/docs

    - name: Get package name
      id: package
      run: | 
        echo "package=$(ls /tmp | grep -i '.tgz' )" >> "$GITHUB_OUTPUT"
        
    - name: Get packagename without extension
      id: packageName
      run: | 
        BASE=${{ steps.package.outputs.package }}
        echo $BASE
        pNAME=${BASE%.*}
        echo $pNAME
        echo "packageName=$pNAME" >> "$GITHUB_OUTPUT"

    - name: Commit index changes to develp branch
      uses: EndBug/add-and-commit@v9
      env:
        GH_TOKEN: ${{ github.token }}
      with:
        new_branch: ci_automation_${{ steps.packageName.outputs.packageName }}
        author_name: Actions_${{ github.actor}}
        message: "Adding ${{ steps.package.outputs.package }} and new index.yaml"
        add: "${{ github.workspace }}/docs/index.yaml ${{ github.workspace }}/docs/${{ steps.package.outputs.package }}"
        
    - name: Create New CI Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --fill \
          --base develop \ 
          --head ci_automation_${{ steps.packageName.outputs.packageName }} \
          --reviewer pj-linebaugh
#     # https://github.com/marketplace/actions/create-pull-request
#     - name: Create New Pull Request
#       uses: peter-evans/create-pull-request@v5
#       with:
#         # Reviewers can be a comma separated list.
#         reviewers: |
#           pj-linebaugh
#           waTeim 
#         title: "Adding ${{ steps.package.outputs.package }} and new index.yaml"
