# Designed to be triggered by github action application chart
name: package-index
on:
  workflow_dispatch:
    inputs:
      appRepo:
        description: 'Repo of the newly updated Helm Chart'
        required: true
        type: string

jobs:
  clone-package-index:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - name: Clone App Repo 
      run: |
        mkdir /tmp/${{ github.repository_owner }}
        cd /tmp/${{ github.repository_owner }}
        git clone https://github.com/${{ inputs.appRepo }}.git .
        pwd 
        ls
        
    # - name: Package Chart 
    #   run: |
    #     cd /tmp/${{ github.repository_owner }}
    #     helm package --dependency-update --destination ${{ github.workspace }}/docs



    # - name: Package 
    #   run: |
        

    # - name: Index 
    #   run: |

#     - name: List files in the repository
#       run: |
#         ls ${{ github.workspace }}

#     - name: Package Chart 
#       run: |
#         helm package --dependency-update ${{ github.workspace }} --destination /tmp/${{ github.repository_owner }}

#     - name: Get package name 
#       id: name 
#       run: |
#         echo "chart_name=$(ls /tmp/${{ github.repository_owner }}/)" >> $GITHUB_OUTPUT
#         ls /tmp/${{ github.repository_owner }}


  # - name: Git pull Helm-Charts Add Repo to /docs
  #   run: |
  #     mkdir /tmp/${{ github.repository_owner }}/helm-charts
  #     cd /tmp/${{ github.repository_owner }}/helm-charts
  #     git clone https://github.com/joshua-seals/helm-charts-test.git .
  #   continue-on-error: true

  # - name: Move & Verify Package  
  #   run: | 
  #     mv /tmp/${{ github.repository_owner }}/${{ steps.name.outputs.chart_name }} /tmp/${{ github.repository_owner }}/helm-charts/docs
  #     ls /tmp/${{ github.repository_owner }}/helm-charts/docs | grep ${{ steps.name.outputs.chart_name }}
