# Designed to be triggered by github action application chart
name: package-index
on:
  workflow_dispatch:
    inputs:
      appRepo:
        description: 'Repo of the newly updated Helm Chart'
        required: true
        type: string

jobs:
  clone-package-index:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }} 
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.11.2

    - name: Clone App Repo 
      run: |
        mkdir /tmp/${{ github.repository_owner }}
        cd /tmp/${{ github.repository_owner }}
        git clone https://github.com/${{ inputs.appRepo }}.git .
        
    - name: Package Chart 
      run: |
        cd /tmp
        helm package --dependency-update ./${{ github.repository_owner }} --destination ${{ github.workspace }}/docs
        helm package --dependency-update ./${{ github.repository_owner }} --destination /tmp

    - name: Index Package 
      run: | 
        helm repo index --merge index.yaml --url=https://helxplatform.github.io/helm-charts/docs ./docs

    - name: Commit to Develop Branch
      env: 
        GH_TOKEN: ${{ github.token }}
      run: |
        package=$(ls /tmp | grep -i '.tgz' )
        git add docs/index.yaml docs/$package
        git commit -m "Adding new $package and index"
        git push origin develop
